server:
  port: 8080
  servlet:
    context-path: /qaute
spring:
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
  application:
    name: QAUTE
  thymeleaf:
    cache: false
  datasource:
    url: jdbc:mysql://localhost:3306/studentconsultingsystem
    username: root
    password: root
  jpa:
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    properties:
      hibernate:
        physical_naming_strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
  task:
    scheduling:
      pool:
        size: 5
    execution:
      pool:
        core-size: 5
        max-size: 10

  mail:
      host: smtp.gmail.com
      port: 587
      username: herothaibao99@gmail.com
      password: nzop khsn iycb rdba
      properties:
        mail:
          smtp:
            auth: true
            starttls:
              enable: true
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${GOOGLE_CLIENT_ID}
            client-secret: ${GOOGLE_CLIENT_SECRET}
            scope: openid, profile, email
            authorization-grant-type: authorization_code
            redirect-uri: "http://localhost:8080/qaute/auth/google/callback"
#            user-name-attribute: sub
            provider: google
        provider:
          google:
            authorization-uri: https://accounts.google.com/o/oauth2/v2/auth
            token-uri: https://oauth2.googleapis.com/token
            user-info-uri: https://www.googleapis.com/oauth2/v3/userinfo
            jwk-set-uri: https://www.googleapis.com/oauth2/v3/certs
jwt:
  signerKey_access: "Ol4TrKY5pNZf+zUjfsgMcjA+7ZphkCRs61AFHtDW/Aq/bmz9QASBYYM/mzAg7dZ5"
  valid-duration: 3600 #in seconds
  refresh-duration: 864000 #in seconds : 10 day
openweather:
  apikey: 8b62d623ee124b44cb88d85bade58e38
cloudinary:
  cloud_name: dob8vleac
  api_key: 428778766855443
  api_secret: iNu_qDEZsruYl8FvZzP0RwjjcqU

event:
  registration:
    cancel:
      hours:
        before: 24
  reminder:
    hours:
      before: 24
    minutes:
      before: 15
  max:
    participants:
      default: 50
  duration:
    min:
      minutes: 30

